package com.example.booksapp

class BooksRepository {
    private var booksList : MutableList<Books> = mutableListOf()

    init{
        booksList.add(Books("Harry Potter 1","Harry Potter se ha quedado huérfano y vive en casa de sus abominables tíos y del insoportable primo Dudley. Se siente muy triste y solo, hasta que un buen día recibe una carta que cambiará su vida para siempre. En ella le comunican que ha sido aceptado como alumno en el colegio interno Hogwarts de magia y hechicería.",""))
        booksList.add(Books("Daisy Jones & The Six","Daisy Jones & The Six sigue a \"una banda de rock en la década de 1970 desde su ascenso en la escena musical de Los Ángeles hasta convertirse en una de las bandas más famosas del mundo y explora la razón detrás de su separación en el apogeo de su éxito\".",""))
        booksList.add(Books("Normal People","Marianne y Connell son compañeros de instituto pero no se cruzan palabra. Él es uno de los populares y ella, una chica solitaria que ha aprendido a mantenerse alejada del resto de la gente. Todos saben que ella vive en una mansión y que él es de origen humilde, pero lo que nadie imagina es que la madre de Connell limpia en casa de Marianne. Allí coinciden los dos cada tarde, hasta que un día, una conversación torpe dará comienzo a una relación que podría cambiar sus vidas. ",""))
        booksList.add(Books("It Ends With Us","A veces, quien más te quiere es quién más daño te hace.\n" + "\n" + "Lily no siempre lo ha tenido fácil. Por eso, su idílica relación con un magnífico neurocirujano llamado Ryle Kincaid, parece demasiado buena para ser verdad. Cuando Atlas, su primer amor, reaparece repentinamente y Ryle comienza a mostrar su verdadera cara, todo lo que Lily ha construido con él se ve amenazado. ",""))
        booksList.add(Books("Heartless","Una historia sobre cómo la Reina de Corazones dejó de soñar con el verdadero amor y la libertad y se convirtió en una cruel mujer. Mucho antes de convertirse en el terror del País de las Maravillas, la Reina de Corazones era una chica que tan solo quería enamorarse... Catherine es una de las jóvenes más deseadas de Corazones. Es la favorita del Rey. Pero ella quiere vivir bajo sus propias reglas y tomar las riendas de su vida. Pero ¿a qué precio?",""))
        booksList.add(Books("The Seven Husbands of Evelyn Hugo","Evelyn Hugo, el ícono de Hollywood que se ha recluido en su edad madura, decide al fin contar la verdad sobre su vida llena de glamour y de escándalos. Pero cuando elige para ello a Monique Grant, una periodista desconocida, nadie se sorprende más que la misma Monique.",""))
        booksList.add(Books("Heartstopper 1","Charlie Spring está en el año 10 en Truham Grammar School for Boys. El año pasado no ha sido muy bueno, pero al menos ya no está siendo intimidado. Nick Nelson está en el año 11 y en el equipo de rugby de la escuela."+ "\n" +"Rápidamente se hacen amigos, y pronto Charlie se enamora de Nick, a pesar de que no cree que tenga ninguna oportunidad. Pero el amor funciona de maneras sorprendentes y, a veces, las cosas buenas esperan a la vuelta de la esquina...",""))
        booksList.add(Books("All This Time","Kyle y Kimberly han sido la pareja perfecta durante toda la escuela secundaria, pero cuando Kimberly rompe con él la noche de su fiesta de graduación, el mundo entero de Kyle da un vuelco, literalmente. Su auto choca y cuando él se despierta, tiene una lesión cerebral. Kimberly está muerta. Y nadie en su vida podría entenderlo.\n" + "\n" + "Hasta Marley. Marley está sufriendo su propia pérdida, una pérdida que cree que fue su culpa. Y cuando sus caminos se cruzan, Kyle ve en ella todas las cosas tácitas que siente.",""))
        booksList.add(Books("Never Saw Me Coming","Conoce a Chloe Sevre. Ella es una estudiante de honor de primer año, que también resulta ser una psicópata. Sus pasatiempos incluyen conspirar para matar a Will Bachman, un amigo de la infancia que la agravió gravemente.\n" + "Chloe es una de los siete estudiantes de su universidad que forman parte de un estudio clínico para psicópatas.\n" + "Cuando uno de los estudiantes del estudio es encontrado asesinado, comienza un peligroso juego del gato y el ratón, y Chloe pasa a ser presa. Mientras se apresura a identificar al asesino y poner en marcha su plan, se verá obligada a decidir si puede confiar en alguno de sus compañeros.",""))
        booksList.add(Books("Divergent","En una ceremonia anual, todos los chicos de dieciseis años deben decidir a que facción dedicarán el resto de sus vidas. Beatrice tiene que elegir entre quedarse con su familia o ser quien realmente es, no puede tener ambas cosas. Así que toma una decisión que sorprenderá a todo el mundo, incluida ella.",""))
        booksList.add(Books("Never Let Me Go"," Hailsham parece un agradable internado inglés, alejado de las influencias de la ciudad. Sus estudiantes están bien atendidos y apoyados, capacitados en arte y literatura, y se convierten en el tipo de personas que el mundo quiere que sean. Pero, curiosamente, no se les enseña nada del mundo exterior y se les permite poco contacto con él.\n" + "\n" + "Dentro de los terrenos de Hailsham, Kathy pasa de ser una colegiala a una mujer joven, pero solo cuando ella y sus amigos Ruth y Tommy abandonan los terrenos seguros de la escuela (como siempre supieron que lo harían) se dan cuenta de la verdad completa de lo que es Hailsham.",""))
        booksList.add(Books("The Picture of Dorian Gray","La víctima es Dorian Gray, un bello y presuntuoso joven a quien un amigo hace un retrato al óleo. Cuando Dorian trabe amistad con lord Henry Wotton, un cínico filósofo, este le convencerá de que sus más valiosas posesiones son su belleza y su juventud. Y, a partir de ahí, su deseo de que su retrato envejezca mientras él permanece joven se hace realidad. Pero ¿a qué precio?Estamos, simple y llanamente, ante uno de los libros más bellos e ingeniosos de todos los tiempos.Luis Antonio de Villena dijo...\n" + "«Un libro lleno de fascinación y encanto, fácil y difícil a la vez, y cuyo único protagonista y tema esencial es la belleza. Una de las pasiones que hacen vivir y dan sentido y fuerza al mundo.»",""))
        booksList.add(Books("Wonder","No describiré cómo me veo. Lo que sea que estés pensando, probablemente sea peor.\n" + "\n" + "August Pullman nació con una diferencia facial que, hasta ahora, le ha impedido ir a una escuela convencional. Comenzando el quinto grado en Beecher Prep, no quiere nada más que ser tratado como un niño común, pero sus nuevos compañeros de clase no pueden pasar por alto la extraordinaria cara de Auggie. Wonder, comienza desde el punto de vista de Auggie, pero pronto cambia para incluir a sus compañeros de clase, su hermana, el novio de ella y otros.",""))
        booksList.add(Books("Crooked Kingdom","Bienvenido al mundo de los Grisha.\n" + "Kaz Brekker y su equipo de parias mortales acaban de llevar a cabo un atraco tan atrevido que ni ellos mismos pensaron que sobrevivirían. Pero en lugar de repartirse una gran recompensa, vuelven a luchar por sus vidas.\n" + "Traicionada y muy debilitada, la tripulación tiene pocos recursos, aliados y esperanza. Mientras poderosas fuerzas de todo el mundo descienden sobre Ketterdam para descubrir los secretos de la peligrosa droga conocida como jurda parem, viejos rivales y nuevos enemigos emergen para desafiar la astucia de Kaz y poner a prueba las frágiles lealtades del equipo.",""))
        booksList.add(Books("La soledad de los números primos","Existen entre los números primos algunos aún más especiales. Son aquellos que los matemáticos llaman primos gemelos, pues entre ellos se interpone siempre un número par. Así, números como el 11 y el 13, el 17 y el 19, o el 41 y el 43, permanecen próximos, pero sin llegar a tocarse nunca. Esta verdad matemática es la hermosa metáfora que el autor ha escogido para narrar la conmovedora historia de Alice y Mattia, dos seres cuyas vidas han quedado condicionadas por las consecuencias irreversibles de sendos episodios ocurridos en su niñez. Desde la adolescencia hasta bien entrada la edad adulta, y pese a la fuerte atracción que indudablemente los une, la vida erigirá entre ellos barreras invisibles que pondrán a prueba la solidez de su relación.",""))
        booksList.add(Books("El Jardin Olvidado","En vísperas de la Primera Guerra Mundial, una niña es abandonada en un barco con destino a Australia. Una misteriosa mujer llamada la Autora ha prometido cuidar de ella, pero la Autora desaparece sin dejar rastro… En la noche de su veintiún cumpleaños, Nell O’Connor descubre que es adoptada, lo que cambiará su vida para siempre. Décadas más tarde, se embarca en la búsqueda de la verdad de sus antepasados...A la muerte de Nell, su nieta Casandra recibe una inesperada herencia: una cabaña y su olvidado jardín en las tierras de Cornualles que es conocido por la gente por los secretos que estos esconden. Aquí es donde Casandra descubrirá finalmente la verdad sobre la familia y resolverá el misterio, que se remonta un siglo, de una niña desaparecida.",""))
        booksList.add(Books("Mujercitas","Mujercitas es una novela escrita por la autora estadounidense Louisa May Alcott. La historia se centra en la vida de cuatro hermanas adolescentes con personalidades muy dispares que, pese a las dificultades, intentan superarse así mismas en el contexto de la Guerra de Secesión.\n",""))
        booksList.add(Books("Percy Jackson y el ladrón del rayo","Cuenta las aventuras de un chico de doce años, Percy Jackson, cuando descubre que es un semidiós; hijo de una mortal y del dios griego, Poseidón. Percy y sus amigos realizan una búsqueda para prevenir una guerra apocalíptica entre los dioses griegos Zeus y Poseidón.\n",""))
        booksList.add(Books("La vida invisible de Addie Larue","Addie abandona su pequeño pueblo natal en la Francia del siglo xviii y comienza un viaje que la lleva por todo el mundo, mientras aprende a vivir una vida en la que nadie la recuerda y todo lo que posee acaba perdido o roto.",""))
        booksList.add(Books("Alicia en el país de las maravillas","La historia cuenta cómo una niña llamada Alicia cae por un agujero, encontrándose en un mundo peculiar y extraño, poblado por humanos y criaturas antropomórficas. El libro juega con la lógica, dando a la novela gran popularidad tanto en niños como en adultos.",""))
        booksList.add(Books("Two can keep a secret","Ellery tiene diecisiete años y una obsesión con el misterio. La hermana gemela de su madre desapareció cuando era adolescente en Echo Bridges, un pueblito de Nueva Inglaterra que ha vuelto a los titulares hace poco por el asesinato de otra chica, la reina del baile del instituto local.",""))
        booksList.add(Books("A good girl’s guide to murder","Esta novela trata sobre una chica llamada Pippa que escoge como tema para un proyecto escolar de preparatoria el asesinato de una chica llamada Andie Bell, y esto hace que empiece a encontrar incongruencias en el caso y acabe metida en una investigación que consume prácticamente todo su tiempo.",""))
        booksList.add(Books("The perks of being a wallflower","Más íntimas que un diario, las cartas de Charlie son singulares y únicas, hilarantes y devastadoras. Todo lo que conocemos sobre ellas es el mundo que comparte. Atrapado entre tratar de vivir su vida secundaria y a la vez huir de ella, Charlie descubre el mundo de las primeras citas, los dramas familiares y nuevos amigos, cuando todo lo que requiere es la canción perfecta en ese impulso perfecto para sentirse infinito.",""))

        booksList.add(Books("Harry Potter 1","Harry Potter se ha quedado huérfano y vive en casa de sus abominables tíos y del insoportable primo Dudley. Se siente muy triste y solo, hasta que un buen día recibe una carta que cambiará su vida para siempre. En ella le comunican que ha sido aceptado como alumno en el colegio interno Hogwarts de magia y hechicería.",""))
        booksList.add(Books("Daisy Jones & The Six","Daisy Jones & The Six sigue a \"una banda de rock en la década de 1970 desde su ascenso en la escena musical de Los Ángeles hasta convertirse en una de las bandas más famosas del mundo y explora la razón detrás de su separación en el apogeo de su éxito\".",""))
        booksList.add(Books("Normal People","Marianne y Connell son compañeros de instituto pero no se cruzan palabra. Él es uno de los populares y ella, una chica solitaria que ha aprendido a mantenerse alejada del resto de la gente. Todos saben que ella vive en una mansión y que él es de origen humilde, pero lo que nadie imagina es que la madre de Connell limpia en casa de Marianne. Allí coinciden los dos cada tarde, hasta que un día, una conversación torpe dará comienzo a una relación que podría cambiar sus vidas. ",""))
        booksList.add(Books("It Ends With Us","A veces, quien más te quiere es quién más daño te hace.\n" + "\n" + "Lily no siempre lo ha tenido fácil. Por eso, su idílica relación con un magnífico neurocirujano llamado Ryle Kincaid, parece demasiado buena para ser verdad. Cuando Atlas, su primer amor, reaparece repentinamente y Ryle comienza a mostrar su verdadera cara, todo lo que Lily ha construido con él se ve amenazado. ",""))
        booksList.add(Books("Heartless","Una historia sobre cómo la Reina de Corazones dejó de soñar con el verdadero amor y la libertad y se convirtió en una cruel mujer. Mucho antes de convertirse en el terror del País de las Maravillas, la Reina de Corazones era una chica que tan solo quería enamorarse... Catherine es una de las jóvenes más deseadas de Corazones. Es la favorita del Rey. Pero ella quiere vivir bajo sus propias reglas y tomar las riendas de su vida. Pero ¿a qué precio?",""))
        booksList.add(Books("The Seven Husbands of Evelyn Hugo","Evelyn Hugo, el ícono de Hollywood que se ha recluido en su edad madura, decide al fin contar la verdad sobre su vida llena de glamour y de escándalos. Pero cuando elige para ello a Monique Grant, una periodista desconocida, nadie se sorprende más que la misma Monique.",""))
        booksList.add(Books("Heartstopper 1","Charlie Spring está en el año 10 en Truham Grammar School for Boys. El año pasado no ha sido muy bueno, pero al menos ya no está siendo intimidado. Nick Nelson está en el año 11 y en el equipo de rugby de la escuela."+ "\n" +"Rápidamente se hacen amigos, y pronto Charlie se enamora de Nick, a pesar de que no cree que tenga ninguna oportunidad. Pero el amor funciona de maneras sorprendentes y, a veces, las cosas buenas esperan a la vuelta de la esquina...",""))
        booksList.add(Books("All This Time","Kyle y Kimberly han sido la pareja perfecta durante toda la escuela secundaria, pero cuando Kimberly rompe con él la noche de su fiesta de graduación, el mundo entero de Kyle da un vuelco, literalmente. Su auto choca y cuando él se despierta, tiene una lesión cerebral. Kimberly está muerta. Y nadie en su vida podría entenderlo.\n" + "\n" + "Hasta Marley. Marley está sufriendo su propia pérdida, una pérdida que cree que fue su culpa. Y cuando sus caminos se cruzan, Kyle ve en ella todas las cosas tácitas que siente.",""))
        booksList.add(Books("Never Saw Me Coming","Conoce a Chloe Sevre. Ella es una estudiante de honor de primer año, que también resulta ser una psicópata. Sus pasatiempos incluyen conspirar para matar a Will Bachman, un amigo de la infancia que la agravió gravemente.\n" + "Chloe es una de los siete estudiantes de su universidad que forman parte de un estudio clínico para psicópatas.\n" + "Cuando uno de los estudiantes del estudio es encontrado asesinado, comienza un peligroso juego del gato y el ratón, y Chloe pasa a ser presa. Mientras se apresura a identificar al asesino y poner en marcha su plan, se verá obligada a decidir si puede confiar en alguno de sus compañeros.",""))
        booksList.add(Books("Divergent","En una ceremonia anual, todos los chicos de dieciseis años deben decidir a que facción dedicarán el resto de sus vidas. Beatrice tiene que elegir entre quedarse con su familia o ser quien realmente es, no puede tener ambas cosas. Así que toma una decisión que sorprenderá a todo el mundo, incluida ella.",""))
        booksList.add(Books("Never Let Me Go"," Hailsham parece un agradable internado inglés, alejado de las influencias de la ciudad. Sus estudiantes están bien atendidos y apoyados, capacitados en arte y literatura, y se convierten en el tipo de personas que el mundo quiere que sean. Pero, curiosamente, no se les enseña nada del mundo exterior y se les permite poco contacto con él.\n" + "\n" + "Dentro de los terrenos de Hailsham, Kathy pasa de ser una colegiala a una mujer joven, pero solo cuando ella y sus amigos Ruth y Tommy abandonan los terrenos seguros de la escuela (como siempre supieron que lo harían) se dan cuenta de la verdad completa de lo que es Hailsham.",""))
        booksList.add(Books("The Picture of Dorian Gray","La víctima es Dorian Gray, un bello y presuntuoso joven a quien un amigo hace un retrato al óleo. Cuando Dorian trabe amistad con lord Henry Wotton, un cínico filósofo, este le convencerá de que sus más valiosas posesiones son su belleza y su juventud. Y, a partir de ahí, su deseo de que su retrato envejezca mientras él permanece joven se hace realidad. Pero ¿a qué precio?Estamos, simple y llanamente, ante uno de los libros más bellos e ingeniosos de todos los tiempos.Luis Antonio de Villena dijo...\n" + "«Un libro lleno de fascinación y encanto, fácil y difícil a la vez, y cuyo único protagonista y tema esencial es la belleza. Una de las pasiones que hacen vivir y dan sentido y fuerza al mundo.»",""))
        booksList.add(Books("Wonder","No describiré cómo me veo. Lo que sea que estés pensando, probablemente sea peor.\n" + "\n" + "August Pullman nació con una diferencia facial que, hasta ahora, le ha impedido ir a una escuela convencional. Comenzando el quinto grado en Beecher Prep, no quiere nada más que ser tratado como un niño común, pero sus nuevos compañeros de clase no pueden pasar por alto la extraordinaria cara de Auggie. Wonder, comienza desde el punto de vista de Auggie, pero pronto cambia para incluir a sus compañeros de clase, su hermana, el novio de ella y otros.",""))
        booksList.add(Books("Crooked Kingdom","Bienvenido al mundo de los Grisha.\n" + "Kaz Brekker y su equipo de parias mortales acaban de llevar a cabo un atraco tan atrevido que ni ellos mismos pensaron que sobrevivirían. Pero en lugar de repartirse una gran recompensa, vuelven a luchar por sus vidas.\n" + "Traicionada y muy debilitada, la tripulación tiene pocos recursos, aliados y esperanza. Mientras poderosas fuerzas de todo el mundo descienden sobre Ketterdam para descubrir los secretos de la peligrosa droga conocida como jurda parem, viejos rivales y nuevos enemigos emergen para desafiar la astucia de Kaz y poner a prueba las frágiles lealtades del equipo.",""))
        booksList.add(Books("La soledad de los números primos","Existen entre los números primos algunos aún más especiales. Son aquellos que los matemáticos llaman primos gemelos, pues entre ellos se interpone siempre un número par. Así, números como el 11 y el 13, el 17 y el 19, o el 41 y el 43, permanecen próximos, pero sin llegar a tocarse nunca. Esta verdad matemática es la hermosa metáfora que el autor ha escogido para narrar la conmovedora historia de Alice y Mattia, dos seres cuyas vidas han quedado condicionadas por las consecuencias irreversibles de sendos episodios ocurridos en su niñez. Desde la adolescencia hasta bien entrada la edad adulta, y pese a la fuerte atracción que indudablemente los une, la vida erigirá entre ellos barreras invisibles que pondrán a prueba la solidez de su relación.",""))
        booksList.add(Books("El Jardin Olvidado","En vísperas de la Primera Guerra Mundial, una niña es abandonada en un barco con destino a Australia. Una misteriosa mujer llamada la Autora ha prometido cuidar de ella, pero la Autora desaparece sin dejar rastro… En la noche de su veintiún cumpleaños, Nell O’Connor descubre que es adoptada, lo que cambiará su vida para siempre. Décadas más tarde, se embarca en la búsqueda de la verdad de sus antepasados...A la muerte de Nell, su nieta Casandra recibe una inesperada herencia: una cabaña y su olvidado jardín en las tierras de Cornualles que es conocido por la gente por los secretos que estos esconden. Aquí es donde Casandra descubrirá finalmente la verdad sobre la familia y resolverá el misterio, que se remonta un siglo, de una niña desaparecida.",""))
        booksList.add(Books("Mujercitas","Mujercitas es una novela escrita por la autora estadounidense Louisa May Alcott. La historia se centra en la vida de cuatro hermanas adolescentes con personalidades muy dispares que, pese a las dificultades, intentan superarse así mismas en el contexto de la Guerra de Secesión.\n",""))
        booksList.add(Books("Percy Jackson y el ladrón del rayo","Cuenta las aventuras de un chico de doce años, Percy Jackson, cuando descubre que es un semidiós; hijo de una mortal y del dios griego, Poseidón. Percy y sus amigos realizan una búsqueda para prevenir una guerra apocalíptica entre los dioses griegos Zeus y Poseidón.\n",""))
        booksList.add(Books("La vida invisible de Addie Larue","Addie abandona su pequeño pueblo natal en la Francia del siglo xviii y comienza un viaje que la lleva por todo el mundo, mientras aprende a vivir una vida en la que nadie la recuerda y todo lo que posee acaba perdido o roto.",""))
        booksList.add(Books("Alicia en el país de las maravillas","La historia cuenta cómo una niña llamada Alicia cae por un agujero, encontrándose en un mundo peculiar y extraño, poblado por humanos y criaturas antropomórficas. El libro juega con la lógica, dando a la novela gran popularidad tanto en niños como en adultos.",""))
        booksList.add(Books("Two can keep a secret","Ellery tiene diecisiete años y una obsesión con el misterio. La hermana gemela de su madre desapareció cuando era adolescente en Echo Bridges, un pueblito de Nueva Inglaterra que ha vuelto a los titulares hace poco por el asesinato de otra chica, la reina del baile del instituto local.",""))
        booksList.add(Books("A good girl’s guide to murder","Esta novela trata sobre una chica llamada Pippa que escoge como tema para un proyecto escolar de preparatoria el asesinato de una chica llamada Andie Bell, y esto hace que empiece a encontrar incongruencias en el caso y acabe metida en una investigación que consume prácticamente todo su tiempo.",""))
        booksList.add(Books("The perks of being a wallflower","Más íntimas que un diario, las cartas de Charlie son singulares y únicas, hilarantes y devastadoras. Todo lo que conocemos sobre ellas es el mundo que comparte. Atrapado entre tratar de vivir su vida secundaria y a la vez huir de ella, Charlie descubre el mundo de las primeras citas, los dramas familiares y nuevos amigos, cuando todo lo que requiere es la canción perfecta en ese impulso perfecto para sentirse infinito.",""))

    }

    fun getBooks () : MutableList<Books>{
        return booksList
    }
}